# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMaximumSize(QtCore.QSize(800, 635))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(60, 140, 431, 381))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_row1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_row1.setObjectName("lineEdit_row1")
        self.gridLayout.addWidget(self.lineEdit_row1, 1, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEdit_1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.gridLayout.addWidget(self.lineEdit_1, 0, 1, 1, 1)
        self.lineEdit_row2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_row2.setObjectName("lineEdit_row2")
        self.gridLayout.addWidget(self.lineEdit_row2, 3, 1, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(520, 140, 221, 381))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_clear = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_clear.setObjectName("btn_clear")
        self.gridLayout_2.addWidget(self.btn_clear, 0, 0, 1, 1)
        self.btn_dot = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_dot.setObjectName("btn_dot")
        self.gridLayout_2.addWidget(self.btn_dot, 4, 0, 1, 1)
        self.btn_t = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_t.setObjectName("btn_t")
        self.gridLayout_2.addWidget(self.btn_t, 3, 0, 1, 1)
        self.btn_det = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_det.setObjectName("btn_det")
        self.gridLayout_2.addWidget(self.btn_det, 1, 0, 1, 1)
        self.btn_inv = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_inv.setObjectName("btn_inv")
        self.gridLayout_2.addWidget(self.btn_inv, 2, 0, 1, 1)
        self.btn_eigvalue = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_eigvalue.setObjectName("btn_eigvalue")
        self.gridLayout_2.addWidget(self.btn_eigvalue, 6, 0, 1, 1)
        self.btn_solve = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_solve.setObjectName("btn_solve")
        self.gridLayout_2.addWidget(self.btn_solve, 5, 0, 1, 1)
        self.btn_var = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_var.setObjectName("btn_var")
        self.gridLayout_2.addWidget(self.btn_var, 7, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 480, 351, 61))
        self.label_5.setObjectName("label_5")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 10, 681, 131))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textEdit_result1 = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.textEdit_result1.setObjectName("textEdit_result1")
        self.horizontalLayout.addWidget(self.textEdit_result1)
        self.textEdit_result2 = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.textEdit_result2.setObjectName("textEdit_result2")
        self.horizontalLayout.addWidget(self.textEdit_result2)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(540, 560, 54, 12))
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "行,列"))
        self.label_2.setText(_translate("MainWindow", "行,列"))
        self.label.setText(_translate("MainWindow", "矩阵一"))
        self.label_3.setText(_translate("MainWindow", "矩阵二"))
        self.btn_clear.setText(_translate("MainWindow", "归零"))
        self.btn_dot.setText(_translate("MainWindow", "矩阵乘法"))
        self.btn_t.setText(_translate("MainWindow", "转置"))
        self.btn_det.setText(_translate("MainWindow", "行列式"))
        self.btn_inv.setText(_translate("MainWindow", "矩阵的逆"))
        self.btn_eigvalue.setText(_translate("MainWindow", "特征值"))
        self.btn_solve.setText(_translate("MainWindow", "解矩阵方程"))
        self.btn_var.setText(_translate("MainWindow", "方差"))
        self.label_5.setText(_translate("MainWindow", "矩阵：从左到右依次输入,逗号隔开\n"
"行列：用逗号隔开,例如:3,4"))
        self.textEdit_result1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">矩阵一的结果</p></body></html>"))
        self.textEdit_result2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">矩阵二的结果</p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))

